notification_page:
  path: /notifications
  defaults: { _controller: AppBundle:Notification:index }

notification_ajax:
  path: /notifications/get
  defaults: { _controller: AppBundle:Notification:countNotifications }